name: Debug Projects v2 → Zapier

on:
  projects_v2_item:
    types: [created, edited, moved]  # ステータス変えたらだいたいこのどれかが来る

jobs:
  relay_raw:
    runs-on: ubuntu-latest
    steps:
      - name: POST raw payload to Zapier
        env:
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: |
          # $GITHUB_EVENT_PATH には今回のイベントJSONが丸ごと入ってます
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            --data-binary @"$GITHUB_EVENT_PATH" \
            "$ZAPIER_HOOK_URL"
