name: タスク（テスト）
description: ←この文が出れば最新テンプレが反映されています
title: "[Task] "
labels: [task]
assignees: []

body:
  - type: input
    id: due
    attributes:
      label: Due date（YYYY-MM-DD）
      placeholder: "2025-08-31"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: ここに背景や目的
    validations:
      required: true