name: タスク
description: Task Management 2025 用タスクを登録
title: "[Task] "
labels: [task]
assignees: []

body:
  - type: input
    id: project
    attributes:
      label: Project（タスクID）
      description: 任意（例: UPJ-300）
      placeholder: "UPJ-300"
    validations:
      required: false

  - type: dropdown
    id: plan_quarter
    attributes:
      label: Plan/Quarter
      options:
        - 2025Q3
        - 2025Q4
        - 2026Q1
        - 2026Q2
        - 2026Q3
        - 2026Q4
    validations:
      required: false

  - type: dropdown
    id: ltp
    attributes:
      label: Long-Term-Project
      options:
        - 雑巾（銀行・掃除など）
        - 人生進捗（美容院・友人と遊ぶなど）
        - 技術書を読む
        - 技術力をつける
    validations:
      required: false

  - type: input
    id: due
    attributes:
      label: Due date（YYYY-MM-DD）
      placeholder: "2025-08-31"
    validations:
      required: false

  - type: input
    id: estimate
    attributes:
      label: Estimate（30分=1）
      placeholder