name: タスク（テスト最小）
description: ←この文がNew issueの選択カードに出ればOK
title: "[Task] "
labels: []
assignees: []
body:
  - type: input
    id: due
    attributes:
      label: Due date（YYYY-MM-DD）
      placeholder: "2025-08-31"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: ここに背景や目的
    validations:
      required: true