name: タスク
description: Task Management 2025 用
title: "[Task] "
labels: []       # ← 最初は空が安定（後で task ラベルを作ってから指定も可）
assignees: []

body:
  - type: input
    id: project
    attributes:
      label: Project（タスクID）
      placeholder: "UPJ-300"

  - type: dropdown
    id: plan-quarter
    attributes:
      label: Plan/Quarter
      options: [2025Q3, 2025Q4, 2026Q1, 2026Q2, 2026Q3, 2026Q4]

  - type: dropdown
    id: long-term-project
    attributes:
      label: Long-Term-Project
      options:
        - 雑巾（銀行・掃除など）
        - 人生進捗（美容院・友人と遊ぶなど）
        - 技術書を読む
        - 技術力をつける

  - type: input
    id: due
    attributes:
      label: Due date（YYYY-MM-DD）
      placeholder: "2025-08-31"

  - type: input
    id: estimate
    attributes:
      label: Estimate（30分=1）
      placeholder: "2"

  - type: textarea
    id: description
    attributes:
      label: Description（背景・受け入れ条件）
      placeholder: |
        背景:
        目的:
        完了条件:
    validations:
      required: true

  - type: textarea
    id: ref
    attributes:
      label: Ref（参考リンク）
      placeholder: |
        - https://example.com
        - 関連Issue: #123

  - type: textarea
    id: todo
    attributes:
      label: Todo（チェックリスト）
      placeholder: |
        - [ ] 手順1
        - [ ] 手順2
