name: タスク（Step1）
description: Plan/Quarter のみ追加した検証版
title: "[Task] "
labels: []
assignees: []
body:
  - type: input
    id: project
    attributes:
      label: Project（タスクID）
      placeholder: "UPJ-300"
    validations:
      required: false

  - type: dropdown
    id: plan-quarter
    attributes:
      label: Plan/Quarter
      options:
        - 2025Q3
        - 2025Q4
        - 2026Q1
        - 2026Q2
        - 2026Q3
        - 2026Q4
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description（背景・受け入れ条件）
      placeholder: |
        背景:
        目的:
        完了条件:
    validations:
      required: true
